### ISSUE TITLE
new feature: Docker REST API (FastAPI) image

### ISSUE THREAD

**Issue by McSim85** [barcus/bareos#112]
Hey Barcus,

Thank you so much for the Docker images.
I would like to suggest a new feature: include a docker image with Bareos REST API access.
So, there is a good doc - https://fossies.org/linux/bareos/rest-api/README.md
I am going to try to make this a Docker image to deploy with all others images by docker-compose.

If you have something in the draft - it would be great.

P.S. I see that this is just experimental status. But let's make it production-ready :)

**Comment by barcus** [comment]
Really interesting, thank you @McSim85 
I'm going to check that really soon :)

**Comment by barcus** [comment]
working fine with my docker-compose

`  bareos-api:
    build: /work/git/bareos/api/20-python
    ports:
      - 8000:8000
    environment:
      - BAREOS_DIR_HOST=bareos-dir`
