### ISSUE TITLE
Update Ubuntu Docker to Bareos 20.0.2

### ISSUE THREAD

**Issue by FlorentPoinsaut** [barcus/bareos#114]
Hi,
Could you please build Ubuntu Docker image in Docker Hub to update Bareos to [20.0.2](https://docs.bareos.org/Appendix/ReleaseNotes.html#id3)  version?
Thanks in advance.
Regards,

**Comment by barcus** [comment]
Hello @FlorentPoinsaut 
Images have been updated. 
Sorry for the late reply, i'm going to plan a scheduled update (each week) soon :)

**Comment by FlorentPoinsaut** [comment]
Hello,
Thanks a lot!
I wish you good luck!
