### ISSUE TITLE
bareos-webui:20-alpine doesn't start the WebUI properly

### ISSUE THREAD

**Issue by andrewmiskell** [barcus/bareos#123]
There appears to be a bug in the packaging of the bareos-webui under nginx for Alpine Edge / BareOS v20 where the bareos-webui.conf file is placed into the /etc/nginx/conf.d directory instead of /etc/nginx/http.d directory. Because of this, it's not read in when nginx starts so the BareOS WebUI never loads.

I've submitted https://gitlab.alpinelinux.org/alpine/aports/-/issues/13019 to Alpine Linux to update the package to put the file in the correct directory. The bareos-webui:20-alpine container will likely need to be rebuilt once the packaging error is fixed.

**Comment by andrewmiskell** [comment]
Fix to the package has been made upstream with Alpine Linux. I've submitted a PR (https://github.com/barcus/bareos/pull/124) to correct the path in the docker-entrypoint.sh for 20-alpine.

**Comment by barcus** [comment]
thank you @andrewmiskell

**Comment by barcus** [comment]
#124 merged
