### ISSUE TITLE
compression alorithm not supported on alpine

### ISSUE THREAD

**Issue by setiseta** [barcus/bareos#13]
Hello,

actually i get on a restore the following message:
30-Aug 15:15 bareos-fd JobId 12127: Error: Compression algorithm 0x465a3448 found, but not supported!

maybe the job was run before i changed to the alpine image.
so it seems there is something missing.

kind regards
sebastian

**Comment by barcus** [comment]
Hello Sebastian

which type of compression are you use in this job ?

i made test to try to reproduce... i ran jobs with gzip compression in BareOS 17.2 (ubuntu based), then i tried to restore them on a fresh BareOS 17.2 (alpine based), no problem !

Regards 
Marc

**Comment by setiseta** [comment]
I'm using LZ4HC.
yes gzip is working.
sorry, i see that i forgot to be more specific in initial text.

**Comment by barcus** [comment]
2020-02-27 00:32:32 | bareos-fd JobId 3: Warning: LZ4HC compression support requested in fileset but not available on this platform. Disabling ...
i can not fix it on my side, sorry :)
