### ISSUE TITLE
Status of Arm64 Support

### ISSUE THREAD

**Issue by Byolock** [barcus/bareos#149]
The description says :

> Alpine images are available for linux/amd64 and linux/arm64/v8 platform

however the php-fpm-alpine image seems to not have an arm64 build :

https://hub.docker.com/r/barcus/php-fpm-alpine/tags

I managed to get to the webui by building an arm64 version myself, but I guess that's not supposed to be that way?

(smtpd is also only available for amd64)

**Comment by barcus** [comment]
thanks for the report @Byolock 
arm64 image is now available for php-fpm
https://github.com/barcus/docker-php-fpm-alpine/commit/0b82b81e69bd6c60e7640fdf36f1e1bfb56d8d4b
can you test is maybe ? :)

i'm going to check about smtp 👍

**Comment by barcus** [comment]
i found a lightweight docker image based on alpine and available for arm arch
i tested it, it works well !
https://registry.hub.docker.com/r/devture/exim-relay

there is just one modification to apply in compose file about smtp host inside director container
`SMTP_HOST=smtpd:8025`
