### ISSUE TITLE
How to fix /dev/tape: No such file or directory

### ISSUE THREAD

**Issue by k3nd0x** [barcus/bareos#152]
Hi @barcus 
First of all thanks for your work 🥇 

But unfortanly I have an issue with the storage daemon on a virtual maschine. (Ubuntu 20.04 LTS) 
A backup job is failing after a few seconds there is an error "error wanted 2000 OK storage, got 2902 Bad storage"

The docker logs of the sd container are saying: 
`chown: /dev/[n]st*: No such file or directory
chown: /dev/tape: No such file or directory
`

It is happening with the newest alpine-psql and the newest ubuntu-psql images :( 

![github](https://user-images.githubusercontent.com/97670834/168103778-52d5b253-17a1-4955-9f53-d1fe254a7956.png)

**Comment by barcus** [comment]
Hi @k3nd0x, thanks for your feedback
This message is just a warning, it's not related to your storage daemon issue, you can ignore it. (chown /dev/*)
I will update docker-entrypoint to avoid this warning when devices does not exist.

Could be great to know why you storage daemon exit.
It looks like you use docker-compose to run the Bareos stack
Can you run `docker-compose up` (without -d) ? in this way bareos-sd will display an error message.
It should be link to bareos storage configuration or your docker-compose file if it exist instantly on start

**Comment by k3nd0x** [comment]
@barcus Thanks for your answer :)
the SD is starting without any problems. `status storage` in bconsole says everything is fine. When i start my first backup job the SD container exits and stops working only the chown failes are showing up in the logs. The SD can read, write & execute to the mounted storage device.

additionally I have to say I installed the bareos-client directly on the maschine (without docker-container) The client is reachable and should not be the problem. 

![bareos-storage](https://user-images.githubusercontent.com/97670834/168230597-7fa63cdb-225d-42af-b6fd-9fe0ce16f460.png)

**Comment by barcus** [comment]
Can you please add this in your compose file before launching an other backup job ?

```
command:
      - "/usr/sbin/bareos-sd"
      - "-u"
      - "bareos"
      - "-f"
      - "-d"
      - "200"

**Comment by k3nd0x** [comment]
Before a backup job:
![bareos](https://user-images.githubusercontent.com/97670834/168278698-7f6cabe5-9eee-42d2-b01d-3f142804cdf5.png)

**Comment by barcus** [comment]
sorry, i will like to see the error when the container exits, during the backup i imagine :)

**Comment by barcus** [comment]
because bareos-sd crashed (exit 139) as we can see in your first screenshot
![Screenshot 2022-05-13 at 17 29 52](https://user-images.githubusercontent.com/3447949/168317255-36ed83b2-78ac-4cf8-be9f-66f82abc4d6d.png)

**Comment by k3nd0x** [comment]
Hi, sorry for the late reply: This is the full logs after starting the container and after the first job:
![bareos1](https://user-images.githubusercontent.com/97670834/168461094-d3f1c8df-4ce3-4d13-918b-d662140102a8.PNG)
![bareos2](https://user-images.githubusercontent.com/97670834/168461095-f0a9cf5a-8167-4806-abb1-8bc10242db2c.PNG)

**Comment by barcus** [comment]
Seems that your storage daemon does not speak to bareos-fd but bareos-dir. I don't know why but i think there is an issue in your configuration.
Take a look on my own logs !
![Screenshot 2022-05-15 at 09 51 18](https://user-images.githubusercontent.com/3447949/168463010-f0c095a7-335c-4ae1-bf8f-2a05ddc6d488.png)

![Screenshot 2022-05-15 at 09 51 18](https://user-images.githubusercontent.com/3447949/168462993-21c4ce04-8f8c-4ad3-9c66-8ea05290dee6.png)

**Comment by k3nd0x** [comment]
Oh shi.. I found it. My client was unable to resolve the name of the bareos-sd ... The name of the SD is "bareos-sd" but my client is running directly on the maschine not in a docker container. So the DNS entry (or /etc/hosts entry) for bareos-sd was missing directly on the maschine. Sorry I bothered you with my config :) but thanks for your help. My backup jobs are running now 💯

**Comment by barcus** [comment]
#153
