### ISSUE TITLE
Image for Bareos Director 18.2 with Postgres?

### ISSUE THREAD

**Issue by PaulLebmann** [barcus/bareos#17]
Hi,
are there any specific reasons that there is no Image for bareos-dir 18.2 with Postgres as database?

Since you made it clear in the documentation for the mysql versions what image uses what Bareos version, maybe you could add a hint also to 
`# image: barcus/bareos-director:pgsql_latest`
in the example docker-compose file.

Thanks a lot!

Paul

**Comment by barcus** [comment]
Hi Paul

No specific reasons, just i don't use it.
The version with Postgres a now available with bareos 18.2 in my repo, also i updated docker-compose files. #21
