### ISSUE TITLE
cant add client Alpine docker

### ISSUE THREAD

**Issue by gudge25** [barcus/bareos#18]
![image](https://user-images.githubusercontent.com/2346208/50910584-c6f14180-1436-11e9-903b-3fa920fc7d9c.png)

Resource config directory "/etc/bareos/bareos-dir-export/client/JiraServer/bareos-fd.d/director/" does not exist.

seems that  docker is not working properly

**Comment by gudge25** [comment]
it is not creating file  in  dir  /etc/bareos/bareos-dir-export/client/

**Comment by barcus** [comment]
Hello,

Unable to reproduce in a fresh install

```#docker exec -t -i bareos_bareos-dir_1 bconsole
Connecting to Director localhost:9101
 Encryption: PSK-AES256-CBC-SHA
1000 OK: bareos-dir Version: 18.2.4rc2 (18 Dec 2018)
You are connected using the default console

Enter a period to cancel a command.
*configure add client name=toto address=192.168.1.55 password=totopassword
Exported resource file "/etc/bareos/bareos-dir-export/client/toto/bareos-fd.d/director/bareos-dir.conf":
Director {
  Name = bareos-dir
  Password = "[md5]f35635f354467414e2a086ff5c3f7740"
}
Created resource config file "/etc/bareos/bareos-dir.d/client/toto.conf":
Client {
  Name = toto
  Address = 192.168.1.55
  Password = totopassword
}
*```

Did you ran bconsole inside your director container ?

**Comment by gudge25** [comment]
forgot to mention --- i use alpine version 
![image](https://user-images.githubusercontent.com/2346208/51113897-579b9900-180c-11e9-9042-eb4186ef1e13.png)

**Comment by barcus** [comment]
it's fixed, Docker image have been updated.
you just need to pull the new one and restart your director container

#23
