### ISSUE TITLE
Bareos FD not start on docker arm64

### ISSUE THREAD

**Issue by eliott3103** [barcus/bareos#180]
Hello, first of all, congratulations on your work and thank you to everyone. I tried to deploy fd on an Orange Pi Zero 2 running Armbian. When I start my Docker Compose, it starts up fine, but then there are no logs, and I can't connect to the container either. Here is my Docker Compose:
version: '3'
services:
  bareos-fd:
    image: barcus/bareos-client:alpine
    container_name: bareos-client
    volumes:
      - /home/media/dockerdata:/etc/bareos
    environment:
      - BAREOS_FD_PASSWORD=mdp
      - FORCE_ROOT=false
   
I'm sorry in advance if my issue is not well formulated or otherwise it's the first time in my life that I open one do not hesitate to tell me if I need to add information or other

**Comment by barcus** [comment]
Hello @eliott3103 

Can you enable debug to check the output ?
It can be done using simple docker run, like this

`docker run -t -i --rm barcus/bareos-client:alpine /usr/sbin/bareos-fd -f -d 200 -dt`

Output should be something like this:

```
31-May-2024 13:11:43.672087 bareos-fd (100): lib/parse_conf.cc:210-0 config file = /etc/bareos/bareos-fd.d/*/*.conf
31-May-2024 13:11:43.672187 bareos-fd (100): lib/lex.cc:316-0 glob /etc/bareos/bareos-fd.d/*/*.conf: 4 files
31-May-2024 13:11:43.672203 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/client/myself.conf
31-May-2024 13:11:43.672214 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
31-May-2024 13:11:43.672231 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/director/bareos-mon.conf
31-May-2024 13:11:43.672244 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/messages/Standard.conf
31-May-2024 13:11:43.672379 bareos-fd (100): lib/lex.cc:316-0 glob /etc/bareos/bareos-fd.d/*/*.conf: 4 files
31-May-2024 13:11:43.672392 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/client/myself.conf
31-May-2024 13:11:43.672401 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
31-May-2024 13:11:43.672415 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/director/bareos-mon.conf
31-May-2024 13:11:43.672427 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/messages/Standard.conf
31-May-2024 13:11:43.674810 bareos-fd (150): filed/fd_plugins.cc:1630-0 plugin dir is NULL
31-May-2024 13:11:43.674859 bareos-fd (10): filed/socket_server.cc:122-0 filed: listening on port 9102
31-May-2024 13:11:43.674879 bareos-fd (10): filed/socket_server.cc:122-0 filed: listening on port 9102
31-May-2024 13:11:43.674892 bareos-fd (100): lib/bnet_server_tcp.cc:152-0 Addresses host[ipv4;0.0.0.0;9102] host[ipv6;::;9102]
```

**Comment by eliott3103** [comment]
Thank you very much for your reply. Here are the debug messages

31-May-2024 19:40:58.320291 bareos-fd (100): lib/parse_conf.cc:210-0 config file = /etc/bareos/bareos-fd.d/*/*.conf
31-May-2024 19:40:58.322124 bareos-fd (100): lib/lex.cc:316-0 glob /etc/bareos/bareos-fd.d/*/*.conf: 4 files
31-May-2024 19:40:58.322531 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/client/myself.conf
31-May-2024 19:40:58.322954 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
31-May-2024 19:40:58.323486 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/director/bareos-mon.conf
31-May-2024 19:40:58.324289 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/messages/Standard.conf
31-May-2024 19:40:58.327563 bareos-fd (100): lib/lex.cc:316-0 glob /etc/bareos/bareos-fd.d/*/*.conf: 4 files
31-May-2024 19:40:58.327952 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/client/myself.conf
31-May-2024 19:40:58.328325 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
31-May-2024 19:40:58.328975 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/director/bareos-mon.conf
31-May-2024 19:40:58.329698 bareos-fd (100): lib/lex.cc:213-0 open config file: /etc/bareos/bareos-fd.d/messages/Standard.conf
31-May-2024 19:40:58.363310 bareos-fd (100): lib/bsys.cc:631-0 Could not open and read state file. size=192: ERR=No such file or directory - iostream error
31-May-2024 19:40:58.363630 bareos-fd (150): filed/fd_plugins.cc:1630-0 plugin dir is NULL
31-May-2024 19:40:58.364289 bareos-fd (10): filed/socket_server.cc:122-0 filed: listening on port 9102
31-May-2024 19:40:58.364628 bareos-fd (10): filed/socket_server.cc:122-0 filed: listening on port 9102
31-May-2024 19:40:58.365092 bareos-fd (100): lib/bnet_server_tcp.cc:152-0 Addresses host[ipv4;0.0.0.0;9102] host[ipv6;::;9102]

**Comment by barcus** [comment]
Looks good to me, Bareos is running and listening on port 9102 !

**Comment by eliott3103** [comment]
Thank you for your reply, but the line :

"31-May-2024 19:40:58.363310 bareos-fd (100): lib/bsys.cc:631-0 Could not open and read state file. size=192: ERR=No such file or directory - iostream error" 

doesn't pose a problem? because when I make a backup from my bareos server I get the connection refused error if I use the docker container but if I go through the classic installation the backup works fine.

**Comment by eliott3103** [comment]
Ok in fact it's my fault I just added ports:- 9102:9102 in my docker-compose and now it works, thanks for your help :)
