### ISSUE TITLE
Not able to find bextract

### ISSUE THREAD

**Issue by jukito** [barcus/bareos#19]
I'm trying to use bextract to plan and test a disaster recovery plan, but i'm not able to find the bextract command inside de directos or the storage container.

There are any way to find/install it?

Thanks a lot!

**Comment by barcus** [comment]
This tool is inside bareos-tools package, which is not currently installed.
I will do it :)

You can install it easily from your host
`docker exec -ti MY_CONTAINER_ID sh -c "apt update && apt -y install bareos-tools"`

**Comment by barcus** [comment]
#20
