### ISSUE TITLE
Troubles with Catalog Backup

### ISSUE THREAD

**Issue by setiseta** [barcus/bareos#2]
Hello,

I'm having troubles with the catalog backup of this container (director).
it seems like the AfterJob runs before the file gets collected.
Do you have recognized similar behavior?

Any hints how to resolve this?

Kind Regards
Sebastian

**Comment by setiseta** [comment]
Ok, nevermind.
I resolved it.
The issue is that the sql file is written in the director to /var/lib/bareos
But the collection was run on bareos-fd
So the file wasen't available there.
I fixed it with a host mount to both container to share this directory.

**Comment by barcus** [comment]
Hello Sebastian
The sql file is generated by bareos-fd in RunBeforeJob of BackupCatalog Job

> # This creates an ASCII copy of the catalog
>   # Arguments to make_catalog_backup.pl are:
>   #  make_catalog_backup.pl <catalog-name>
>   RunBeforeJob = "/usr/lib/bareos/scripts/make_catalog_backup.pl MyCatalog"

If you use the file on the director, make sure it is up to date, with a fresh dump
There is a problem in my image about this, I will fix it quickly

Regards,
Marc

**Comment by setiseta** [comment]
Hello Marc,

thank you for the reply.
But as far is i have seen, the file was generated in the director container.
And the fd try's to backup the file after the before job, but cause it is generated in the director container, the file was missing in the fd container.
so i connected this dir togheter.
this seems to work for the moment.

I've tested this behavior with disabling the afterjob, so that the file gets not deleted, and i searched it, and found it on the director.

so maybe it is enough to generate a shared volume for this dir.

Regards,
Sebastian
