### ISSUE TITLE
Fresh install  bareos-dir  stopped 

### ISSUE THREAD

**Issue by gudge25** [barcus/bareos#22]
using this file https://github.com/barcus/bareos/blob/master/docker-compose.yml
fresh install dir stopped 
![image](https://user-images.githubusercontent.com/2346208/51114640-97fc1680-180e-11e9-899e-b7d1ca6799c3.png)

**Comment by barcus** [comment]
unable to reproduce on my side...
everything looks good inside /var/lib/bareos (permissions and file...)

i use: 
docker-compose version 1.23.2, build 1110ad01
Docker version 18.09.1, build 4c52b90

**Comment by gudge25** [comment]
ok i am done after removing dir 
/home/bareos/config/director
and 
/home/bareos/data/director 
(seems to be conflict  from alpine version)
