### ISSUE TITLE
Bareos 18.2.5 is out

### ISSUE THREAD

**Issue by setiseta** [barcus/bareos#25]
An update of the docker images would be great.

**Comment by jukito** [comment]
Hi @barcus. In a friendly way, do you plan to upgrade to 18.2.5 in the near future?

Thanks a lot and excuse us for the impatience.

**Comment by barcus** [comment]
images was updated 

docker exec -t -i build_bareos-dir_1 bconsole
Connecting to Director localhost:9101
 Encryption: PSK-AES256-CBC-SHA
1000 OK: bareos-dir Version: 18.2.5 (30 January 2019)
