### ISSUE TITLE
bareos-webui timeout / not working

### ISSUE THREAD

**Issue by PaulLebmann** [barcus/bareos#26]
Hello,

in the last few weeks bareos-webui didn't work for me.
If I try to login with my credentials I get redirected to the dashboard URL and if I use the wrong credentials I get the username / password error. Therefore, and since I already adapted my config, I don't think this is related to #24 

I got it working again by adding the new bareos release key to the container and updating all the packages including bareos-webui. If I destroy the container and use the original image the issue (of course) reappears. I assume it could be related to [this reported bareos bug.](https://bugs.bareos.org/view.php?id=1033) 

I use the ubuntu version of the image on a host running ubuntu 18.04 with docker-ce 18.09.2.

It seems a bit strange that no one has reported the issue yet, so maybe it's somehow just my setup.

best regards,

Paul

**Comment by PaulLebmann** [comment]
Hi again,

I tried to create a pull request and realized there is nothing to be done. Those who build their images themselves won't have a problem since the url for the new repo - key did not change. So if you build all the images yourself you already have the fixed version of bareos-webui.

For those who use the images from @barcus and set their passwords via environment variables triggering a rebuild of the image would be helpful.

thanks for your work!

Paul

**Comment by PaulLebmann** [comment]
Seems you triggered a rebuild. My Issue is gone. Thank you!!

**Comment by barcus** [comment]
> Seems you triggered a rebuild. My Issue is gone. Thank you!!

thanks for your feedback Paul
regards,
Marc
