### ISSUE TITLE
Storage Director Doesn't Have Tape Library Tools Installed

### ISSUE THREAD

**Issue by joltman80** [barcus/bareos#27]
I'd like to use a tape library with your container.  I've had to manually install it within the container, but that's not sustainable moving forward.  I used to following inside the container:

apt install bareos-storage-tape mtx scsitools sg3-utils mt-st

Would it be possible to add these to your SD container docker build?  Thank you!

**Comment by barcus** [comment]
i will take a look, if it's not too big :)

**Comment by wucke13** [comment]
@barcus Can you confirm whether the tape library tools are available in the alpine image?
