### ISSUE TITLE
ARM-compatible build

### ISSUE THREAD

**Issue by lukas-mertens** [barcus/bareos#28]
It would be nice to have a docker-build for ARM processors, e.g. to use bareos on a raspberry pi. As far as I understand this would only require changing the downloaded packages in the docker-files to arm-compatible ones. What do you think?

**Comment by gasparakos** [comment]
Yes, it would be good. I would have tried it on our Helios4.

**Comment by barcus** [comment]
Alpine images are now available for amd64 and arm64 platform, enjoy !
