### ISSUE TITLE
docker-compose failing with postgres, permission error opening PID 

### ISSUE THREAD

**Issue by triptronics** [barcus/bareos#29]
Hi there, I think there was already an issue listed here (#9) for this but the issue is still not resolved. The only way to get this working was to chmod my Bareos directory on my host to 777. I don't feel that this is a proper solution. What is the most secured, preferred way to handle this issue? How can it be fixed on the container side? Thank you.

**Comment by barcus** [comment]
#30

**Comment by barcus** [comment]
> Hi there, I think there was already an issue listed here (#9) for this but the issue is still not resolved. The only way to get this working was to chmod my Bareos directory on my host to 777. I don't feel that this is a proper solution. What is the most secured, preferred way to handle this issue? How can it be fixed on the container side? Thank you.

it's done, i updated entry-point script to fix permissions when /var/lib/bareos is mount with wrong permissions

**Comment by triptronics** [comment]
Ok, thank you :)
