### ISSUE TITLE
smtpd is not configured properly on 18.2 version

### ISSUE THREAD

**Issue by Dark-Vex** [barcus/bareos#31]
I did noticed that on the version 18.2 the ${SMTP_HOST} variable is no properly replaced in 
- /etc/bareos/bareos-dir.d/messages/Daemon.conf
- /etc/bareos/bareos-dir.d/messages/Standard.conf

This is because on the default files there is "root@localhost" as host instead of only "localhost" so this cause sed command to fail to replace the string.
This happen only on 18.2, on the 17.2 it works properly

This is the default config
```
root@somehost:/home/bareos # grep -r "/usr/bin/bsmtp -h root@localhost" ./config/director/bareos-dir.d/messages/Standard.conf
./config/director/bareos-dir.d/messages/Standard.conf:  operatorcommand = "/usr/bin/bsmtp -h root@localhost -f \"\(Bareos\) \<%r\>\" -s \"Bareos: Intervention needed for %j\" %r"
./config/director/bareos-dir.d/messages/Standard.conf:  mailcommand = "/usr/bin/bsmtp -h root@localhost -f \"\(Bareos\) \<%r\>\" -s \"Bareos: %t %e of %c %l\" %r"
```

**Comment by barcus** [comment]
Thank you @Dark-Vex
