### ISSUE TITLE
Image tags mismatch in README.md

### ISSUE THREAD

**Issue by Dark-Vex** [barcus/bareos#45]
I did noticed that there is a mismatch in the tags, if you use the tag 18, it will deploy the director with PostgreSQL instead of MySQL. In the README file it says that should deploy the director with MySQL but If I take a look on docker hub (https://hub.docker.com/r/barcus/bareos-director/tags) the tags 18 and 18-pgsql-ubuntu have the same digest.
So I suppose that the README file is wrong

**Comment by barcus** [comment]
Sorry, i have a work in progress job about CI. it fixed, 18 is mysql version, will not change
