### ISSUE TITLE
17.2

### ISSUE THREAD

**Issue by setiseta** [barcus/bareos#5]
Hello,

are there any plans to update this repo to the new release 17.2?

Kind Regards
Sebastian

**Comment by barcus** [comment]
Hi Sebastian,

I made some updates for 17.2 last night, like auto upgrade MySQL database.
If you use the 'latest' tag you only need to rebuild your images.
I created new tags too, like 'mysql_16' to force bareos-director in version 16.2 with MySQL

Regards,

Mark
