### ISSUE TITLE
package tzdata

### ISSUE THREAD

**Issue by 85humberto** [barcus/bareos#59]
Hi there.

I'm using the images 18-ubuntu-pgsql and 18-ubuntu. The new images don't have the package tzdata. The old images was work correctly with env "TZ".
Could you build the images with tzdata package again?

Thanks.

**Comment by barcus** [comment]
Hi
Previously images was based on my own ubuntu which contains tzdata. Will add it for ubuntu images :)

**Comment by barcus** [comment]
build in progress #60
