### ISSUE TITLE
docker-compose-ubuntu-pgsql.yml up with error

### ISSUE THREAD

**Issue by minh10huy** [barcus/bareos#62]
After docker-compose-ubuntu-pgsql-yml up then encounter error the following:
bareos-dir: ERROR TERMINATION at lib/parse_conf_state_machine.cc:213

Contents in webui-admin.conf and admin.conf files something wrong.
data/bareos/config/director/bareos-dir.d/profile/webui-admin.conf 
<a href="/bareos/bareos/master/webui/install/bareos/bareos-dir.d/profile/webui-admin.conf">Moved Permanently</a>.

Regards,

**Comment by minh10huy** [comment]
My solution way is copy running config files in the others 

cat /etc/bareos/bareos-dir.d/profile/webui-admin.conf
#
# bareos-webui webui-admin profile resource
#
Profile {
  Name = webui-admin
  Command ACL = !.bvfs_clear_cache, !.exit, !.sql
  Command ACL = !configure, !create, !delete, !purge, !sqlquery, !umount, !unmount
  Command ACL = *all*

  Catalog ACL = *all*
  Client ACL = *all*
  FileSet ACL = *all*
  Job ACL = *all*
  Pool ACL = *all*
  Schedule ACL = *all*
  Storage ACL = *all*
  Where ACL = *all*
}
cat /etc/bareos/bareos-dir.d/console/admin.conf
#
# Restricted console used by bareos-webui
#
Console {
  Name = admin
  Password = "roundSt@r83"
  Profile = "webui-admin"
  TLS Enable = No
}

**Comment by barcus** [comment]
Those files are downloaded from official Bareos repo.
It looks like an url issue in docker entrypoint.
i'm gonna check

**Comment by barcus** [comment]
Thanks for the feedback @minh10huy 
It will be fixed and closed soon :)
