### ISSUE TITLE
env SMTP_HOST and ADMIN_MAIL aren't replaced

### ISSUE THREAD

**Issue by opelx** [barcus/bareos#67]
Hello,
while playing with email the compose snippet:

          bareos-dir:
            image: barcus/bareos-director:19-ubuntu-pgsql
            ...
            environment:
              - SMTP_HOST=mail.example.net
              - SENDER_MAIL=bareos@example.net #optional
              - ADMIN_MAIL=bareos@example.net
            ...

results into

        $ cat Standard.conf
        Messages {
          Name = Standard
          Description = "Reasonable message delivery -- send most everything to email address and to the console."
          operatorcommand = "/usr/bin/bsmtp -h localhost -f \"\(Bareos\) \<bareos.example.net\>\" -s \"Bareos: Intervention needed for %j\" %r"
          mailcommand = "/usr/bin/bsmtp -h localhost -f \"\(Bareos\) \<bareos.example.net\>\" -s \"Bareos: %t %e of %c %l\" %r"
          operator = root = mount                                 # (#03)
          mail = root = all, !skipped, !saved, !audit             # (#02)
          console = all, !skipped, !saved, !audit
          append = "/var/log/bareos/bareos.log" = all, !skipped, !saved, !audit
          catalog = all, !skipped, !saved, !audit
        }

        $ cat Daemon.conf
        Messages {
          Name = Daemon
          Description = "Message delivery for daemon messages (no job)."
          mailcommand = "/usr/bin/bsmtp -h localhost -f \"\(Bareos\) \<bareos.example.net\>\" -s \"Bareos daemon message\" %r"
          mail = root = all, !skipped, !audit # (#02)
          console = all, !skipped, !saved, !audit
          append = "/var/log/bareos/bareos.log" = all, !skipped, !audit
          append = "/var/log/bareos/bareos-audit.log" = audit
        }

As far I can see, the sed expression has been changed from root@localhost over the time.

**Comment by jahegu** [comment]
I haev the same problem

**Comment by barcus** [comment]
#72
