### ISSUE TITLE
ERR=Permission denied for backup jobs using bareos-fd

### ISSUE THREAD

**Issue by triptronics** [barcus/bareos#71]
Hi there, hope you are doing well and staying safe! We are trying to use the bareos-fd image to backup files with Bareos. We mount the directories we want to backup from the host computer to the container and then we run the job. For almost every file, we recieve the following error: ERR=Permission denied and nothing gets backed up. We changed the init.d/bareos-fd file to run with root user and group root and still nothing. We can't change the permissions on the folders itself because they are on the host and that can mess something up. Is there a better way we can do this or is there a fix for the permission denied error? Thank you so much!

**Comment by barcus** [comment]
Hi there.
Do you speak about reading file or writing file ?

**Comment by barcus** [comment]
#86
