### ISSUE TITLE
Introduce Slack/Telegram notifications and Prometheus Exporter

### ISSUE THREAD

**Issue by dark-vex** [barcus/bareos#73]
Hey @barcus, would be interesting for you in having the support for WebHook notifications like Slack or Telegram and Prometheus Exporter?
At the moment I've a prototype for Slack notifications but I need to integrate it with docker-compose.
If you think it might be useful I will create a pull request once is ready.
This is what I have so far when the backup is OK or Fail on Slack

<img width="1087" alt="Screenshot 2020-08-17 at 14 25 46" src="https://user-images.githubusercontent.com/2905124/90396129-f8f86a00-e095-11ea-9fd4-718d8fd4c108.png">
<img width="1087" alt="Screenshot 2020-08-17 at 14 27 31" src="https://user-images.githubusercontent.com/2905124/90396134-fac22d80-e095-11ea-88f5-fb42ad186def.png">

**Comment by barcus** [comment]
Hey @Dark-Vex 
I like the idea of Prometheus exporter and notifications through webhook yes :)

**Comment by Dark-Vex** [comment]
Nice! Next week should I have some free time for doing that :)

**Comment by barcus** [comment]
Thank you @dark-vex
