### ISSUE TITLE
add bareos user to floppy group in bareos-sd

### ISSUE THREAD

**Issue by wucke13** [barcus/bareos#80]
Hi, I would like to use my autochanger with this excellent dockerized bareos setup. However, the the device file for both the autochanger and the tape drive are owned by `root:floppy` (in the ubuntu image). However, the bareos user in said container is only part of the following groups:

+ `bareos`
+ `disk`
+ `tape`

Hence accessing the tape or the changer does not work. So either the `bareos` user would have to be added to `floppy` group, or the udev rules would have to be changed to chown tape drives and autochangers to the `tape` group.

**Comment by barcus** [comment]
#81
