### ISSUE TITLE
Running client/bareos-fd as root?

### ISSUE THREAD

**Issue by wucke13** [barcus/bareos#82]
Hi, I would like to run bareos-fd in it's container as root. However, if I add `user: root` to it's section in the `docker-compose.yml`, bareos still ends up running as user `bareos`. This creates issues, as some file in my backup can only be accessed through the `root` user. What would be the solution for this issue? Does `bareos` itself drop the privileges by running it self under another user?

**Comment by barcus** [comment]
HI @wucke13 this part is defined inside CMD command of each dockerfile (bareos -u bareos)
it could be easily modified with an env variable through docker-compose, at least for root user :)
So finaly it could be great to integrate #77 which is related i think, i have to think about that
